name = "spring"
main = "index.js"
compatibility_date = "2025-11-09"
workers_dev = true
preview_urls = true
logpush = false
send_metrics = false
minify = false

[dev]
port = 5000
ip = "0.0.0.0"
local_protocol = "http"

[vars]
UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
PROXYIP = "nima.nscl.ir"

# [build]
# command = "npm run deploy"

# [[rules]]
# type = "ESModule"
# globs = ["**/*.js"]
